---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# idsst.rtutorials

<!-- badges: start -->
<!-- badges: end -->

`idsst.rtutorials` contains several R tutorials. The mandatory tutorials for the IDSST course are:

+ programming-basics
+ data-and-visualization
+ data-wrangling
+ exploratory-data-analysis
+ explore-cat-data
+ explore-num-data


Additional (not mandatory) topics are discussed in the tutorials:

+ customize
+ line-graphs
+ overplotting
+ scatterplots


## Installation

You can install the development version of idsst.rtutorials from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("hgstp/idsst.rtutorials")
```


### Credits

The tutorials were originally created by the [RStudio Education](https://github.com/rstudio-education) team and published under Creative Commons Attribution-ShareAlike 4.0 License (CC BY-SA 4.0). We changed the name of all tutorials and adjusted the links for all vimeo videos.
None of these and all other changes have been approved in any way by the RStudio education.
